# Generated by Django 3.0.6 on 2020-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='session_key',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
